import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#012d1d",
        "on-tertiary-fixed": "#400100",
        "on-secondary-fixed": "#2d1600",
        background: "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed-variant": "#274e3d",
        "on-secondary-container": "#764200",
        "on-tertiary-container": "#ff826e",
        "secondary-container": "#feb063",
        "on-primary-fixed": "#002114",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-surface-variant": "#414844",
        tertiary: "#550200",
        "surface-dim": "#dcd9d9",
        "primary-fixed": "#c1ecd4",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "surface-container-highest": "#e5e2e1",
        outline: "#717973",
        "text-outline": "#717973",
        "tertiary-fixed-dim": "#ffb4a7",
        "tertiary-container": "#7b0e04",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c1c8c2",
        surface: "#fcf9f8",
        "tertiary-fixed": "#ffdad4",
        "on-primary-container": "#86af99",
        "inverse-primary": "#a5d0b9",
        "secondary-fixed-dim": "#ffb873",
        error: "#ba1a1a",
        "on-background": "#1c1b1b",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#6a3b00",
        "surface-tint": "#3f6653",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdcbf",
        "surface-container-high": "#eae7e7",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0eded",
        "primary-fixed-dim": "#a5d0b9",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-tertiary-fixed-variant": "#8a1a0e",
        "primary-container": "#1b4332",
        "inverse-surface": "#313030",
        secondary: "#8b5006",
        "inverse-on-surface": "#f3f0ef",
        amber: "#feb063",
        forest: "#012d1d",
        cream: "#fcf9f8",
        mist: "#f1ede4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        lg: "48px",
        gutter: "24px",
        md: "24px",
        "margin-desktop": "64px",
        xs: "4px",
        "margin-mobile": "20px",
        xl: "80px",
        base: "8px",
        sm: "12px",
      },
      fontFamily: {
        "headline-md": ["var(--font-fraunces)", "Georgia", "serif"],
        "label-md": ["var(--font-inter)", "Arial", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Arial", "sans-serif"],
        "headline-lg-mobile": ["var(--font-fraunces)", "Georgia", "serif"],
        "headline-xl-mobile": ["var(--font-fraunces)", "Georgia", "serif"],
        "headline-lg": ["var(--font-fraunces)", "Georgia", "serif"],
        "body-lg": ["var(--font-inter)", "Arial", "sans-serif"],
        "body-md": ["var(--font-inter)", "Arial", "sans-serif"],
        "headline-xl": ["var(--font-fraunces)", "Georgia", "serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-xl-mobile": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-xl": ["60px", { lineHeight: "1.1", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
